language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r-packages:
- shape 
- knitr

r_github_packages:
- jokergoo/GlobalOptions

r_check_args: --no-vignettes --no-build-vignettes

