language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r-packages:
- GlobalOptions
- shape 
- knitr

r_check_args: --no-vignettes --no-build-vignettes

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'

